// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Promo {
  /**
   * Code type
   */
  codeType: 
  | {
      /**
       * Selected
       */
      _selected: "unique";

      /**
       * Unique codes
       */
      unique: {
        /**
         * Codes
         */
        unique: Array<{
          /**
           * Code
           */
          code: string;

          /**
           * Used
           */
          used: boolean;
        }>;
      }
    }
  | {
      /**
       * Selected
       */
      _selected: "same";

      /**
       * Single with multiple usages
       */
      same: {
        /**
         * Code
         */
        code: string;

        /**
         * Codes amount
         */
        amount?: number;
      }
    };

  /**
   * Discount
   */
  discount: number;

  /**
   * Type
   */
  type: "percent" | "value";
}
