// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Product {
  /**
   * Composition
   */
  composition?: string;

  /**
   * Current price
   */
  price: number;

  /**
   * Final price
   */
  finalPrice?: number;

  /**
   * Item type
   */
  type: "ticket" | "clothes" | "poster";

  /**
   * Main image
   */
  mainImage: string;

  /**
   * Swatch image
   */
  swatch: string;

  /**
   * Variations
   */
  variations?: Array<string>;

  /**
   * Images
   */
  images?: Array<string>;

  /**
   * Description
   */
  description?: string;

  /**
   * Inventory
   */
  inventory?: number;

  /**
   * Available sizes
   */
  sizes?: Array<{
    /**
     * Size
     */
    title: string;

    /**
     * Amount
     */
    amount?: number;

    /**
     * A size
     */
    asize?: string;

    /**
     * B size
     */
    bsize?: string;
  }>;

  /**
   * Weight
   */
  weight: number;

  /**
   * Digital
   */
  digital: boolean;

  /**
   * Preorder
   */
  preorder: boolean;

  /**
   * Discontinued
   */
  discontinued: boolean;

  /**
   * Show size grid
   */
  showSizeGrid: boolean;

  /**
   * Theme
   */
  theme?: string;

  /**
   * Ticket type
   */
  ticketType?: "regularTicket2020" | "legendaryTicket2020" | "regularTicket" | "legendaryTicket" | "kostiConnectTurbo" | "kostiConnectOnline";

  /**
   * Ids amount
   */
  generateIds?: number;

  /**
   * Hashtags
   */
  hashtags?: Array<string>;
}
